# permissions for end users to edit projectsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: projectset-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: projectset-operator
    app.kubernetes.io/part-of: projectset-operator
    app.kubernetes.io/managed-by: kustomize
  name: projectset-editor-role
rules:
- apiGroups:
  - project.migrx.io
  resources:
  - projectsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.migrx.io
  resources:
  - projectsets/status
  verbs:
  - get
