---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - networkpolicy
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - role
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - project.migrx.io
  resources:
  - projectsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.migrx.io
  resources:
  - projectsets/finalizers
  verbs:
  - update
- apiGroups:
  - project.migrx.io
  resources:
  - projectsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - project.migrx.io
  resources:
  - projectsetsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - project.migrx.io
  resources:
  - projectsetsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - project.migrx.io
  resources:
  - projectsetsyncs/status
  verbs:
  - get
  - patch
  - update
