apiVersion: project.migrx.io/v1alpha1
kind: ProjectSetTemplate
metadata:
  labels:
    app.kubernetes.io/name: projectsettemplate
    app.kubernetes.io/instance: dev-small
    app.kubernetes.io/part-of: projectset-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectset-operator
  name: dev-small
spec:

  labels:
    stage: dev-from-template
  annotations:
    app.kubernetes.io/template: dev-small

  roles:
    developer:
      - apiGroups:
          - ""
          - apps
        resources:
          - configmaps
          - deployments
          - pods
          - pods/log
        verbs: ["*"]

    admin:
      - apiGroups:
          - ""
          - apps
          - autoscaling
          - batch
          - extensions
          - policy
          - rbac.authorization.k8s.io
          - networking.k8s.io
          - storage.k8s.io
          - metrics.k8s.io
        resources:
          - configmaps
          - daemonsets
          - deployments
          - events
          - endpoints
          - jobs
          - pods
          - pods/log
          - pods/exec
          - persistentvolumes
          - persistentvolumeclaims
          - secrets
          - serviceaccounts
          - services
          - statefulsets
        verbs: ["*"]

  roleBindings:
    admin:
      - kind: "Group"
        name: "developer"
      - kind: "Group"
        name: "admin"
    developer:
      - kind: "Group"
        name: "developer"

  resourceQuota:
    hard:
      requests.cpu: "2"
      requests.memory: 3Gi
      limits.cpu: "4"
      limits.memory: 6Gi

  limitRange:
    limits:
      - default:
          cpu: 500m
          memory: "50Mi"
        defaultRequest:
          cpu: 500m
          memory: "50Mi"
        max:
          cpu: "1"
          memory: "4Gi"
        min:
          cpu: 100m
          memory: "50Mi"
        type: Container

  networkPolicy:

    allow-dns:
      podSelector:
        matchLabels: {}
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        ports:
        - protocol: UDP
          port: 53

    deny-egress:
      podSelector:
        matchLabels: {}
      policyTypes:
        - Egress

    deny-ingress:
      podSelector:
        matchLabels: {}
      policyTypes:
        - Egress
