apiVersion: project.migrx.io/v1alpha1
kind: ProjectSet
metadata:
  labels:
    app.kubernetes.io/name: projectset
    app.kubernetes.io/instance: projectset
    app.kubernetes.io/part-of: projectset-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectset-operator
  name: devteam-projectset
spec:
  namespace: dev-app
  labels:
    app: frontend
    stage: dev
  annotations:
    app.kubernetes.io/name: dev-app 
    app.kubernetes.io/lang: golang 
  resourceQuota:
    hard:
      requests.cpu: "2"
      requests.memory: 3Gi
      limits.cpu: "4"
      limits.memory: 5Gi
  limitRange:
    limits:
      - default:
          cpu: 500m
          memory: "50Mi"
        defaultRequest:
          cpu: 500m
          memory: "50Mi"
        max:
          cpu: "1"
          memory: "1Gi"
        min:
          cpu: 100m
          memory: "50Mi"
        type: Container
