apiVersion: project.migrx.io/v1alpha1
kind: ProjectSetTemplate
metadata:
  labels:
    app.kubernetes.io/name: projectsettemplate
    app.kubernetes.io/instance: projectsettemplate-sample
    app.kubernetes.io/part-of: projectset-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectset-operator
  name: projectsettemplate-sample
spec:
  # TODO(user): Add fields here
