apiVersion: project.migrx.io/v1alpha1
kind: ProjectSet
metadata:
  labels:
    app.kubernetes.io/name: projectset
    app.kubernetes.io/instance: projectset
    app.kubernetes.io/part-of: projectset-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projectset-operator
  name: devteam-projectset
spec:
  namespace: dev-app
  labels:
    app: frontend
    stage: dev
  annotations:                                                                                                 
    app.kubernetes.io/name: dev-app                                                                            
    app.kubernetes.io/lang: golang

  roleRules:
    developer:
      - apiGroups:
          - ""
          - apps
          - metrics.k8s.io
        resources:
          - configmaps
          - daemonsets
          - deployments
          - events
          - pods
          - pods/log
          - pods/exec
          - statefulsets
        verbs: ["*"]

    admin:
      - apiGroups:
          - ""
          - apps
          - autoscaling
          - batch
          - extensions
          - policy
          - rbac.authorization.k8s.io
          - networking.k8s.io
          - storage.k8s.io
          - metrics.k8s.io
        resources:
          - configmaps
          - daemonsets
          - deployments
          - events
          - endpoints
          - jobs
          - pods
          - pods/log
          - pods/exec
          - persistentvolumes
          - persistentvolumeclaims
          - secrets
          - serviceaccounts
          - services
          - statefulsets
        verbs: ["*"]

  groupPermissions:
    admin:
      - kind: "Group"
        name: "developer"
      - kind: "Group"
        name: "admin"
    developer:
      - kind: "Group"
        name: "developer"
